"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type Webhook = { id: string; label: string; urlHint: string; notificationTypes: string[]; isActive: boolean; lastSuccessAt: string | null; lastErrorMessage: string | null };
const notificationOptions = [
  ["EVENT_PUBLISHED", "Event published"], ["SIGNUPS_CLOSED", "Signups closed"], ["CHECK_IN_OPEN", "Check-in opened"], ["EVENT_LIVE", "Event started"], ["EVENT_COMPLETED", "Event completed"], ["EVENT_CANCELLED", "Event cancelled"], ["BRACKET_PUBLISHED", "Bracket published"],
] as const;

export function WorkspaceWebhookForm({ workspaceId, webhooks }: { workspaceId: string; webhooks: Webhook[] }) {
  const router = useRouter(); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState("");
  async function add(formData: FormData) {
    setBusy("new"); setMessage("");
    try { const response = await fetch(`/api/workspaces/${workspaceId}/webhooks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label: formData.get("label"), url: formData.get("url"), usernameOverride: formData.get("usernameOverride"), avatarUrl: formData.get("avatarUrl"), notificationTypes: notificationOptions.filter(([value]) => formData.get(value) === "on").map(([value]) => value) }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Webhook could not be saved."); setMessage("Webhook saved securely. Send a test before relying on it."); router.refresh(); }
    catch (error) { setMessage(error instanceof Error ? error.message : "Webhook could not be saved."); }
    finally { setBusy(null); }
  }
  async function test(id: string) { setBusy(id); setMessage(""); try { const response = await fetch(`/api/workspaces/${workspaceId}/webhooks/${id}/test`, { method: "POST" }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Webhook test failed."); setMessage("Test message delivered to Discord."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Webhook test failed."); } finally { setBusy(null); } }
  async function remove(id: string) { if (!window.confirm("Delete this webhook connection?")) return; setBusy(id); setMessage(""); try { const response = await fetch(`/api/workspaces/${workspaceId}/webhooks?webhookId=${encodeURIComponent(id)}`, { method: "DELETE" }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error ?? "Webhook could not be deleted."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Webhook could not be deleted."); } finally { setBusy(null); } }
  return <div className="section-stack"><div className="request-list">{webhooks.map((webhook) => <article className="list-card webhook-card" key={webhook.id}><span className="list-icon">WH</span><div><strong>{webhook.label}</strong><span>{webhook.urlHint}</span><p>{webhook.notificationTypes.length ? webhook.notificationTypes.map((item) => item.replaceAll("_", " ").toLowerCase()).join(" · ") : "No automatic messages selected"}</p>{webhook.lastSuccessAt ? <small>Last success: {new Date(webhook.lastSuccessAt).toLocaleString()}</small> : null}{webhook.lastErrorMessage ? <small className="error-text">{webhook.lastErrorMessage}</small> : null}</div><div className="button-row"><button className="button button-secondary" type="button" onClick={() => test(webhook.id)} disabled={busy === webhook.id}>Test</button><button className="button button-danger" type="button" onClick={() => remove(webhook.id)} disabled={busy === webhook.id}>Delete</button></div></article>)}</div><form className="card form-stack" action={add}><h3>Connect a Discord webhook</h3><p className="muted">The full webhook URL is encrypted and never shown again. Webhooks can post announcements but cannot read Discord, assign roles, or send private DMs.</p><div className="two-column"><div className="form-stack compact"><label htmlFor="webhook-label">Private label</label><input id="webhook-label" name="label" placeholder="Event announcements" required /></div><div className="form-stack compact"><label htmlFor="webhook-url">Discord webhook URL</label><input id="webhook-url" name="url" type="url" placeholder="https://discord.com/api/webhooks/..." required /></div></div><div className="two-column"><div className="form-stack compact"><label htmlFor="webhook-username">Sender name</label><input id="webhook-username" name="usernameOverride" placeholder="Game Night Tools" /></div><div className="form-stack compact"><label htmlFor="webhook-avatar">Sender avatar URL</label><input id="webhook-avatar" name="avatarUrl" type="url" placeholder="https://..." /></div></div><div className="settings-check-grid">{notificationOptions.map(([value, label]) => <label className="checkbox-row" key={value}><input name={value} type="checkbox" defaultChecked={value === "EVENT_PUBLISHED" || value === "EVENT_COMPLETED" || value === "BRACKET_PUBLISHED"} />{label}</label>)}</div><button className="button" disabled={busy === "new"}>{busy === "new" ? "Saving…" : "Save webhook"}</button></form>{message ? <p className="form-message">{message}</p> : null}</div>;
}
